# Generated by Django 5.1.7 on 2025-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_ticket_totem_alter_line_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
